qBit_HOST: "placeholder"

credentials:
  username: "placeholder"
  password: "placeholder"

SHOW_CSV_PATH: shows.csv

FULL_BATCH_THRESHOLD: 1.5

BASE_URL: 'https://nyaa.si/?'
TABLE_CLASS: 'table table-bordered table-hover table-striped torrent-list'