qBit_HOST: 'placeholder'

credentials:
  username: "placeholder"
  password: "placeholder"

SHOW_CSV_PATH: showdata/shows.csv

BASE_PLEX_PATH: "placeholder"

FULL_BATCH_THRESHOLD: 1.5

BASE_URL: 'https://nyaa.si/?'
TABLE_CLASS: 'table table-bordered table-hover table-striped torrent-list'